project:
  type: website # Tells quarto to build a website
  output-dir: _site # Tells it to place the rendered site in _site/

website:
  title: "OOP code for parsing baryon results"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: input_data.qmd
        text: Input data sources

format: # Global default options for the html output
  html:
    theme: cosmo
    toc: true # toc = table of contents
