project:
  type: website # Tells quarto to build a website
  output-dir: docs # Tells it to place the rendered site in docs/

website:
  title: "OOP code for parsing baryon results"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format: # Global default options for the html output
  html:
    theme: cosmo
    toc: true # toc = table of contents
